FROM node:22-bookworm-slim AS build

WORKDIR /app

ARG VITE_SERVER_ENDPOINT
ENV VITE_SERVER_ENDPOINT=$VITE_SERVER_ENDPOINT

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build


FROM node:22-bookworm-slim AS runtime

WORKDIR /app

RUN npm install -g serve@14

COPY --from=build /app/dist ./dist

EXPOSE 5173

CMD ["serve", "-s", "dist", "-l", "5173", "--no-clipboard"]
