services:
  volt-server:
    build: !reset null
    image: ghcr.io/voltlabs-research/volt-server-stack:${VOLT_IMAGE_TAG:-main}

  volt-client:
    build: !reset null
    image: ghcr.io/voltlabs-research/volt-client-stack:${VOLT_IMAGE_TAG:-main}

  cluster-daemon:
    build: !reset null
    image: ghcr.io/voltlabs-research/volt-cluster-daemon-stack:${CLUSTER_DAEMON_IMAGE_TAG:-main}
