import 'reflect-metadata';
import { DAEMON_TOKENS } from './tokens';
import { loadConfig } from './config';
import { RuntimeEventBroker } from '../infrastructure/RuntimeEventBroker';
import { DockerRuntimeService } from '../infrastructure/docker/DockerRuntimeService';
import { MinioService } from '../infrastructure/minio/MinioService';
import { MongoConnectionRepository } from '../infrastructure/mongo/repositories/MongoConnectionRepository';
import { NotebookRepository } from '../infrastructure/mongo/repositories/NotebookRepository';
import { PluginListingRepository } from '../infrastructure/mongo/repositories/PluginListingRepository';
import { QueueService } from '../infrastructure/redis/QueueService';
import { RedisConnectionService } from '../infrastructure/redis/RedisConnectionService';
import { AnalysisWorker } from '../modules/analysis/AnalysisWorker';
import { BinaryExecutorService } from '../modules/analysis/BinaryExecutorService';
import { PluginBinaryCacheService } from '../modules/analysis/PluginBinaryCacheService';
import { ResultProcessorService } from '../modules/analysis/ResultProcessorService';
import { JupyterRuntimeService } from '../modules/jupyter/JupyterRuntimeService';
import { MetricsService } from '../modules/metrics/MetricsService';
import { FilterEvaluatorService } from '../modules/native/FilterEvaluatorService';
import { GlbExporterService } from '../modules/native/GlbExporterService';
import { NativeModuleLoader } from '../modules/native/NativeModuleLoader';
import { RasterizerService } from '../modules/native/RasterizerService';
import { TrajectoryParserService } from '../modules/native/TrajectoryParserService';
import { FileExtractorService } from '../modules/ssh-import/FileExtractorService';
import { SSHConnectionService } from '../modules/ssh-import/SSHConnectionService';
import { SSHImportWorkerService } from '../modules/ssh-import/SSHImportWorkerService';
import { DaemonSocketServer } from '../websocket/DaemonSocketServer';
import { VoltCloudConnection } from '../websocket/VoltCloudConnection';
import { container } from 'tsyringe';

export const registerDaemonDependencies = () => {
    const config = loadConfig();

    container.registerInstance(DAEMON_TOKENS.Config, config);

    container.registerSingleton(DAEMON_TOKENS.RuntimeEventBroker, RuntimeEventBroker);
    container.registerSingleton(DAEMON_TOKENS.RedisConnection, RedisConnectionService);
    container.registerSingleton(DAEMON_TOKENS.QueueService, QueueService);
    container.registerSingleton(DAEMON_TOKENS.MongoConnection, MongoConnectionRepository);
    container.registerSingleton(DAEMON_TOKENS.TrajectoryRepository, PluginListingRepository);
    container.registerSingleton(DAEMON_TOKENS.AnalysisJobRepository, PluginListingRepository);
    container.registerSingleton(DAEMON_TOKENS.NotebookRepository, NotebookRepository);
    container.registerSingleton(DAEMON_TOKENS.MinioService, MinioService);
    container.registerSingleton(DAEMON_TOKENS.DockerRuntimeService, DockerRuntimeService);
    container.registerSingleton(DAEMON_TOKENS.NativeModuleLoader, NativeModuleLoader);
    container.registerSingleton(DAEMON_TOKENS.TrajectoryParserService, TrajectoryParserService);
    container.registerSingleton(DAEMON_TOKENS.GlbExporterService, GlbExporterService);
    container.registerSingleton(DAEMON_TOKENS.RasterizerService, RasterizerService);
    container.registerSingleton(DAEMON_TOKENS.FilterEvaluatorService, FilterEvaluatorService);
    container.registerSingleton(DAEMON_TOKENS.AnalysisWorker, AnalysisWorker);
    container.registerSingleton(DAEMON_TOKENS.BinaryExecutorService, BinaryExecutorService);
    container.registerSingleton(DAEMON_TOKENS.ResultProcessorService, ResultProcessorService);
    container.registerSingleton(DAEMON_TOKENS.PluginBinaryCacheService, PluginBinaryCacheService);
    container.registerSingleton(DAEMON_TOKENS.SSHConnectionService, SSHConnectionService);
    container.registerSingleton(DAEMON_TOKENS.SSHImportWorkerService, SSHImportWorkerService);
    container.registerSingleton(DAEMON_TOKENS.FileExtractorService, FileExtractorService);
    container.registerSingleton(DAEMON_TOKENS.MetricsService, MetricsService);
    container.registerSingleton(DAEMON_TOKENS.JupyterRuntimeService, JupyterRuntimeService);
    container.registerSingleton(DAEMON_TOKENS.VoltCloudConnection, VoltCloudConnection);
    container.registerSingleton(DAEMON_TOKENS.DaemonSocketServer, DaemonSocketServer);
};

export { container };
