export const DAEMON_TOKENS = Object.freeze({
    Config: Symbol.for('DaemonConfig'),
    RuntimeEventBroker: Symbol.for('RuntimeEventBroker'),
    RedisConnection: Symbol.for('RedisConnection'),
    QueueService: Symbol.for('QueueService'),
    MongoConnection: Symbol.for('MongoConnection'),
    TrajectoryRepository: Symbol.for('TrajectoryRepository'),
    AnalysisJobRepository: Symbol.for('AnalysisJobRepository'),
    NotebookRepository: Symbol.for('NotebookRepository'),
    MinioService: Symbol.for('MinioService'),
    DockerRuntimeService: Symbol.for('DockerRuntimeService'),
    NativeModuleLoader: Symbol.for('NativeModuleLoader'),
    TrajectoryParserService: Symbol.for('TrajectoryParserService'),
    GlbExporterService: Symbol.for('GlbExporterService'),
    RasterizerService: Symbol.for('RasterizerService'),
    FilterEvaluatorService: Symbol.for('FilterEvaluatorService'),
    AnalysisWorker: Symbol.for('AnalysisWorker'),
    BinaryExecutorService: Symbol.for('BinaryExecutorService'),
    ResultProcessorService: Symbol.for('ResultProcessorService'),
    PluginBinaryCacheService: Symbol.for('PluginBinaryCacheService'),
    SSHConnectionService: Symbol.for('SSHConnectionService'),
    SSHImportWorkerService: Symbol.for('SSHImportWorkerService'),
    FileExtractorService: Symbol.for('FileExtractorService'),
    MetricsService: Symbol.for('MetricsService'),
    JupyterRuntimeService: Symbol.for('JupyterRuntimeService'),
    VoltCloudConnection: Symbol.for('VoltCloudConnection')
});
