export const PLUGIN_TOKENS = {
    PluginRepository: Symbol.for('PluginRepository'),
    PluginListingService: Symbol.for('PluginListingService'),
    WorkflowValidatorService: Symbol.for('WorkflowValidatorService'),
    ListingRowPrecomputationService: Symbol.for('ListingRowPrecomputationService'),
    ListingRowRepository: Symbol.for('ListingRowRepository'),
    SubListingRowRepository: Symbol.for('SubListingRowRepository'),
    NodeRegistry: Symbol.for('NodeRegistry'),
    PluginStorageService: Symbol.for('PluginStorageService'),
    DefaultPluginBootstrapService: Symbol.for('DefaultPluginBootstrapService'),
    PluginBinaryCacheService: Symbol.for('PluginBinaryCacheService'),
    ListingRowsExportPresenter: Symbol.for('ListingRowsExportPresenter'),
    PluginExposureExportService: Symbol.for('PluginExposureExportService'),
    PluginWorkflowEngine: Symbol.for('WorkflowEngine'),
    ProcessExecutorService: Symbol.for('ProcessExecutorService'),
    AnalysisProcessingQueue: Symbol.for('AnalysisProcessingQueue'),
    AnalysisJobFactory: Symbol.for('AnalysisJobFactory'),
    DebugSocketModule: Symbol.for('DebugSocketModule'),
    ModifierHandler: Symbol.for('ModifierHandler'),
    ArgumentsHandler: Symbol.for('ArgumentsHandler'),
    ContextHandler: Symbol.for('ContextHandler'),
    ForEachHandler: Symbol.for('ForEachHandler'),
    EntrypointHandler: Symbol.for('EntrypointHandler'),
    ExposureHandler: Symbol.for('ExposureHandler'),
    ExportHandler: Symbol.for('ExportHandler'),
    IfStatementHandler: Symbol.for('IfStatementHandler')
} as const;
