import DownloadTeamClusterRemoteExplorerObjectUseCase from '@modules/cluster/application/use-cases/DownloadTeamClusterRemoteExplorerObjectUseCase';
import { createPreparedDownloadStreamController } from '@shared/infrastructure/http/controllers/createController';

export default createPreparedDownloadStreamController(DownloadTeamClusterRemoteExplorerObjectUseCase);
