
export const DOMAIN_EVENTS = Object.freeze({
    AnalysisCreated: 'analysis.created',
    AnalysisDeleted: 'analysis.deleted',
    AnalysisStageChanged: 'analysis.stage.changed',
    AnalysisStatusChanged: 'analysis.status.changed',
    UserCreated: 'user.created',
    UserDeleted: 'user.deleted',
    ChatDeleted: 'chat.deleted',
    UserActivityRecorded: 'user-activity.recorded',
    ContainerCreated: 'container.created',
    ContainerDeleted: 'container.deleted',
    ContainerUpdated: 'container.updated',
    JobStatusChanged: 'job.status.changed',
    LatexDocumentCreated: 'latex-document.created',
    LatexDocumentDeleted: 'latex-document.deleted',
    LatexFileContentUpdated: 'latex-file.content.updated',
    PluginCreated: 'plugin.created',
    PluginDeleted: 'plugin.deleted',
    PluginPublished: 'plugin.published',
    PluginExecutionRequest: 'PluginExecutionRequest',
    NotebookDeleted: 'notebook.deleted',
    TeamCreated: 'team.created',
    TeamDeleted: 'team.deleted',
    TeamMemberDeleted: 'team-member.deleted',
    TeamRoleCreated: 'team-role.created',
    TeamRoleDeleted: 'team-role.deleted',
    TeamRoleUpdated: 'team-role.updated',
    SecretKeyCreated: 'secret-key.created',
    SecretKeyDeleted: 'secret-key.deleted',
    InvitationSent: 'invitation.sent',
    TrajectoryCreated: 'trajectory.created',
    TrajectoryDeleted: 'trajectory.deleted',
    TrajectoryUpdated: 'trajectory.updated',
    SceneArtifactBatchUpserted: 'scene-artifact.upserted',
    WhiteboardCreated: 'whiteboard.created',
    WhiteboardDeleted: 'whiteboard.deleted'
});
