import { collectAllowedClientOrigins } from '@shared/infrastructure/utilities/client-origins';
import type { IncomingHttpHeaders } from 'node:http';
import type { Response } from 'express';

/**
 * Builds the `frame-ancestors` CSP directive that allows the VOLT client to
 * embed a proxied upstream UI (e.g. a Jupyter notebook, or any container app
 * surfaced in-app) inside an <iframe>. Allowed origins come from CLIENT_HOST /
 * CLIENT_DEV_HOST (loopback aliases expanded by collectAllowedClientOrigins).
 */
export const buildFrameAncestorsDirective = (): string => {
    const frameAncestors = new Set<string>(['\'self\'']);

    for (const origin of collectAllowedClientOrigins([process.env.CLIENT_HOST, process.env.CLIENT_DEV_HOST])) {
        frameAncestors.add(origin);
    }

    return `frame-ancestors ${Array.from(frameAncestors).join(' ')}`;
};

/**
 * Rewrites an upstream `Content-Security-Policy` so its `frame-ancestors`
 * directive permits embedding in the VOLT client. Any pre-existing
 * `frame-ancestors` directive is dropped and replaced; other directives are
 * preserved. When the upstream has no CSP, the bare directive is returned.
 */
export const rewriteFrameAncestorsDirective = (contentSecurityPolicy?: string): string => {
    const frameAncestorsDirective = buildFrameAncestorsDirective();
    if (!contentSecurityPolicy?.trim()) {
        return frameAncestorsDirective;
    }

    const directives = contentSecurityPolicy
        .split(';')
        .map((directive) => directive.trim())
        .filter(Boolean)
        .filter((directive) => !directive.toLowerCase().startsWith('frame-ancestors'));

    directives.push(frameAncestorsDirective);
    return directives.join('; ');
};

/**
 * Mutates a mutable upstream header map (as exposed by `http-proxy`'s
 * `proxyRes.headers`) so the response can be embedded in the VOLT client:
 * the `frame-ancestors` CSP is rewritten and `X-Frame-Options` is stripped.
 */
export const applyEmbeddableHeadersToProxyResponse = (headers: IncomingHttpHeaders): void => {
    const upstreamContentSecurityPolicy = Array.isArray(headers['content-security-policy'])
        ? headers['content-security-policy'][0]
        : headers['content-security-policy'];

    headers['content-security-policy'] = rewriteFrameAncestorsDirective(upstreamContentSecurityPolicy);
    delete headers['x-frame-options'];
};

/**
 * Applies the embeddable security headers to an Express response directly
 * (used on error responses generated by the proxy itself, before the upstream
 * headers are available).
 */
export const applyEmbeddableHeadersToResponse = (res: Response, upstreamContentSecurityPolicy?: string): void => {
    res.removeHeader('x-frame-options');
    res.removeHeader('content-security-policy');
    res.setHeader('Content-Security-Policy', rewriteFrameAncestorsDirective(upstreamContentSecurityPolicy));
};
