export const TEAM_TOKENS = Object.freeze({
    TeamHttpService: Symbol.for('TeamHttpService'),
    TeamMemberHttpService: Symbol.for('TeamMemberHttpService'),
    TeamRoleHttpService: Symbol.for('TeamRoleHttpService'),
    TeamInvitationHttpService: Symbol.for('TeamInvitationHttpService'),
    SecretKeyHttpService: Symbol.for('SecretKeyHttpService'),
    TeamAIIntegrationHttpService: Symbol.for('TeamAIIntegrationHttpService'),
    TeamRepository: Symbol.for('TeamRepository'),
    TeamMemberRepository: Symbol.for('TeamMemberRepository'),
    TeamRoleRepository: Symbol.for('TeamRoleRepository'),
    TeamInvitationRepository: Symbol.for('TeamInvitationRepository'),
    SecretKeyRepository: Symbol.for('SecretKeyRepository'),
    SecretKeyUsageLogRepository: Symbol.for('SecretKeyUsageLogRepository'),
    TeamAIIntegrationRepository: Symbol.for('TeamAIIntegrationRepository'),
    TeamAIProviderCatalog: Symbol.for('TeamAIProviderCatalog'),
    SecretKeyUsageMetricsMapper: Symbol.for('SecretKeyUsageMetricsMapper'),
    TeamMembershipService: Symbol.for('TeamMembershipService'),
    TeamRoomPresenceService: Symbol.for('TeamRoomPresenceService'),
    DefaultTeamEnroller: Symbol.for('DefaultTeamEnroller')
});
