export const TEAM_TOKENS = Object.freeze({
    TeamRoleRepository: Symbol.for('TeamRoleRepository'),
    TeamMemberRepository: Symbol.for('TeamMemberRepository'),
    TeamRepository: Symbol.for('TeamRepository'),
    SecretKeyRepository: Symbol.for('SecretKeyRepository'),
    SecretKeyUsageLogRepository: Symbol.for('SecretKeyUsageLogRepository'),
    TeamAIIntegrationRepository: Symbol.for('TeamAIIntegrationRepository'),
    TeamInvitationRepository: Symbol.for('TeamInvitationRepository'),
    TeamJobsService: Symbol.for('TeamJobsService'),
    TeamPresenceService: Symbol.for('TeamPresenceService'),
    TeamJobsSocketModule: Symbol.for('TeamJobsSocketModule'),
    TeamPresenceSocketModule: Symbol.for('TeamPresenceSocketModule'),
    TeamAIProviderCatalog: Symbol.for('TeamAIProviderCatalog'),
    TeamAIIntegrationInputService: Symbol.for('TeamAIIntegrationInputService'),
    TeamAIIntegrationSecretCipher: Symbol.for('TeamAIIntegrationSecretCipher'),
    TeamAIIntegrationSecretService: Symbol.for('TeamAIIntegrationSecretService'),
    TeamAIIntegrationSerializer: Symbol.for('TeamAIIntegrationSerializer'),
    TeamMembershipService: Symbol.for('TeamMembershipService'),
    SecretKeyUsageMetricsMapper: Symbol.for('SecretKeyUsageMetricsMapper')
});