#!/usr/bin/env bash
# rebuild-daemon.sh – Rebuild the local ClusterDaemon image and recreate only the
# daemon service for an installed team cluster.
#
# Non-daemon services (MinIO, Redis, MongoDB) are not restarted.
#
# Usage:
#   ./rebuild-daemon.sh <clusterId> [installRoot] [daemonSrcPath]
#
# Arguments:
#   clusterId      Required. The cluster ID to target.
#   installRoot    Optional. Root directory where clusters are installed.
#                  Defaults to /opt/volt/team-clusters.
#   daemonSrcPath  Optional. Path to the local ClusterDaemon source directory.
#                  Defaults to the parent directory of this script (app/ClusterDaemon).
#
# Example:
#   ./rebuild-daemon.sh 69b20648911ca488bbb759bb
#   ./rebuild-daemon.sh 69b20648911ca488bbb759bb /opt/volt/team-clusters
#   ./rebuild-daemon.sh 69b20648911ca488bbb759bb /opt/volt/team-clusters /home/user/repos/Volt/app/ClusterDaemon

set -euo pipefail

CLUSTER_ID="${1:?Usage: rebuild-daemon.sh <clusterId> [installRoot] [daemonSrcPath]}"
INSTALL_ROOT="${2:-/opt/volt/team-clusters}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DAEMON_SRC="${3:-$(cd "$SCRIPT_DIR/.." && pwd)}"

CLUSTER_DIR="${INSTALL_ROOT}/${CLUSTER_ID}"
OVERRIDE_FILE="${CLUSTER_DIR}/docker-compose.local-rebuild.yml"

# ---------------------------------------------------------------------------
# Prerequisite checks
# ---------------------------------------------------------------------------

if ! command -v docker &>/dev/null; then
    echo "Error: docker is not installed or not in PATH." >&2
    exit 1
fi

if [ ! -d "$CLUSTER_DIR" ]; then
    echo "Error: Cluster directory not found: ${CLUSTER_DIR}" >&2
    exit 1
fi

if [ ! -f "${CLUSTER_DIR}/docker-compose.yml" ]; then
    echo "Error: docker-compose.yml not found in ${CLUSTER_DIR}" >&2
    exit 1
fi

if [ ! -d "$DAEMON_SRC" ]; then
    echo "Error: Daemon source directory not found: ${DAEMON_SRC}" >&2
    exit 1
fi

echo "Rebuilding daemon for cluster : ${CLUSTER_ID}"
echo "  Install directory            : ${CLUSTER_DIR}"
echo "  Daemon source                : ${DAEMON_SRC}"
echo ""

# ---------------------------------------------------------------------------
# Temporary compose override
#
# The generated cluster compose file may reference the daemon via 'image' only,
# without a 'build' context.  Writing a temporary override file injects a local
# build context for the daemon service without permanently modifying the
# generated manifest.  Docker Compose merges the two files so that the built
# image is tagged with the same image name already in the base compose file.
# ---------------------------------------------------------------------------

cat > "$OVERRIDE_FILE" <<EOF
# Temporary override generated by rebuild-daemon.sh – safe to delete.
services:
  daemon:
    build:
      context: "${DAEMON_SRC}"
    pull_policy: build
EOF

# Remove the temporary override file when the script exits (success or failure).
trap 'rm -f "$OVERRIDE_FILE"' EXIT

# ---------------------------------------------------------------------------
# Rebuild and recreate only the daemon service
# ---------------------------------------------------------------------------

cd "$CLUSTER_DIR"

docker compose \
    -f docker-compose.yml \
    -f "$OVERRIDE_FILE" \
    up -d --no-deps --build daemon

echo ""
echo "Daemon service rebuilt and recreated successfully for cluster ${CLUSTER_ID}."
