import {
    createBurstRateLimiter,
    createExportRateLimiter,
    createGeneralRateLimiter,
    createStandardRateLimiter
} from '@shared/infrastructure/http/middleware/rate-limit';

export const RATE_LIMIT_POLICIES = {
    aiConversationCreate: createStandardRateLimiter(20),
    aiConversationMessage: createBurstRateLimiter(10, 60 * 1000),
    analysisDelete: createStandardRateLimiter(30),
    authPublic: createStandardRateLimiter(15),
    chatFileSend: createBurstRateLimiter(5, 60 * 1000),
    chatGroupAddUsers: createStandardRateLimiter(20),
    chatGroupCreate: createStandardRateLimiter(10),
    chatMessageSend: createBurstRateLimiter(30, 60 * 1000),
    colorCodingApply: createStandardRateLimiter(15),
    containerCreate: createStandardRateLimiter(5),
    containerDelete: createStandardRateLimiter(10),
    dailyActivityRead: createGeneralRateLimiter(60),
    jobsMutation: createStandardRateLimiter(5),
    notificationAccess: createGeneralRateLimiter(60),
    particleFilterApply: createStandardRateLimiter(15),
    passwordUpdate: createStandardRateLimiter(5, 'Too many password attempts, please try again later'),
    pluginClone: createStandardRateLimiter(10),
    pluginCreate: createStandardRateLimiter(15),
    pluginExecute: createStandardRateLimiter(10),
    pluginExport: createExportRateLimiter(10),
    pluginImport: createStandardRateLimiter(3),
    rasterTrigger: createStandardRateLimiter(3),
    scriptingSessionCreate: createStandardRateLimiter(5),
    simulationCellRead: createGeneralRateLimiter(60),
    sshConnectionCreate: createStandardRateLimiter(10),
    sshConnectionTest: createStandardRateLimiter(10),
    systemAccess: createGeneralRateLimiter(60),
    teamAIIntegrationCreate: createStandardRateLimiter(5),
    teamClusterCreate: createStandardRateLimiter(5),
    teamClusterDelete: createStandardRateLimiter(5, 'Too many delete attempts, please try again later'),
    teamClusterLifecycle: createStandardRateLimiter(30, 'Too many team cluster lifecycle requests, please try again later'),
    teamClusterRevealCredentials: createStandardRateLimiter(5, 'Too many credential reveal attempts, please try again later'),
    teamCreate: createStandardRateLimiter(5),
    teamDelete: createStandardRateLimiter(5),
    teamInvitationSend: createStandardRateLimiter(10),
    teamMemberRemoval: createStandardRateLimiter(10),
    teamRoleCreate: createStandardRateLimiter(10),
    teamSecretKeyCreate: createStandardRateLimiter(5),
    trajectoryUpload: createStandardRateLimiter(5)
};
